accounts:
  - name: treasury
    coins: ["140000000ZEST", "100000000stkZEST"]
  - name: shulgin
    coins: ["9950000ZEST"]
  - name: rancidrocker24
    coins: ["50000ZEST"]
validator:
  name: treasury
  staked: "100000000stkZEST"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: treasury
  coins: ["100ZEST"]
  coins_max: ["1000ZEST"]
  rate_limit_window: "604800s"
genesis:
  chain_id: "zestchain"
  app_state:
    staking:
      params:
        bond_denom: "stkZEST"
host:
  api: "0.0.0.0:80"
