accounts:
  - name: treasury
    coins: ["50000000ZEST", "100000000ZESTAKE"]
  - name: shulgin
    coins: ["10000000ZEST"]
  - name: rancidrocker24
    coins: ["50000ZEST"]
validator:
  name: treasury
  staked: "100000000ZESTAKE"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: treasury
  coins: ["10ZEST"]
genesis:
  chain_id: "zestchain"
  app_state:
    staking:
      params:
        bond_denom: "ZESTAKE"

